variable "gcp_project_id" {} 
variable "provider_region" {}
variable "ip_name" {}
variable "subnet_region" {} 
variable "sql_machine_type" {}
variable "vpc_name" {}
variable "dataset_id" {}
variable "bq_friendly_name" {}
variable "bq_location" {}
variable "bq_owner_email" {}
variable "bucket_name" {}
variable "bucket_location" {}
variable "bucket_class" {}
